language: rust
sudo: false

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

rust:
  - stable
  - beta
  - nightly
  - 1.6.0

before_script:
  - |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo --only stable build -- --features hasher &&
      travis-cargo --only stable test -- --features hasher &&
      travis-cargo --only stable doc -- --features hasher
after_success:
  - travis-cargo --only stable doc-upload
  - travis-cargo coveralls --no-sudo

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE="hasher"
    - secure: kWv9GF+ZWtq4tNpbCubnIc4NV437dTHhPBent03aEYs6I2tPfX6AiVsb69tIxyLkmFypGdRo7T+7G78mpUWHX7rgBnHG+91Qv/0Nj9TRE7U04pLKerq88pix8apivWatdlUnhOzd86tTnYp6H9LP9gUSTmBCyFcKIuRAZFH1sZg=
  email: false
