[package]
name = "murmurhash64"
version = "0.1.1"
authors = ["Jan-Erik Rediger <badboy@archlinux.us>"]
description = "Implementation of MurmurHash2 (64bit version)"
homepage = "https://github.com/badboy/murmurhash64-rs"
license = "BSD-3-Clause"
readme = "README.md"
